# Generated by Django 4.2 on 2024-11-15 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('recording_id', models.CharField(max_length=200, unique=True)),
                ('output_path', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('recording', 'Recording'), ('stopped', 'Stopped'), ('error', 'Error')], default='initializing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
                ('filepath', models.CharField(max_length=255)),
                ('filesize', models.BigIntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('fps', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['ticket_id', 'agent_name', 'status'], name='recordings__ticket__fd80e6_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['recording_id'], name='recordings__recordi_c54094_idx'),
        ),
    ]
